#!/usr/bin/env python3
"""omabinds transactional controller. Standard library only; JSON IPC over stdin."""
from __future__ import annotations
import base64
import configparser
import contextlib
import ctypes
import fcntl
import hashlib
import json
import os
from pathlib import Path
import re
import shlex
import shutil
import subprocess
import sys
import tempfile
import uuid

ROOT = Path(__file__).resolve().parent.parent
PLUGIN_ID = 'pablousx.omabinds'
MODS = {'SUPER': 64, 'CTRL': 4, 'ALT': 8, 'SHIFT': 1, 'MOD5': 128, 'MOD3': 32}
ALIASES = {'CONTROL': 'CTRL', 'MOD4': 'SUPER', 'WIN': 'SUPER', 'META': 'SUPER', 'MOD1': 'ALT'}
BEGIN = '-- BEGIN omabinds '


class Error(Exception):
    pass


def run(args, **kwargs):
    p = subprocess.run(args, text=True, capture_output=True, timeout=30, **kwargs)
    if p.returncode:
        raise Error((p.stdout + p.stderr or f'{args[0]} failed ({p.returncode})')[-5000:])
    return p.stdout


def atomic(path, text):
    path = Path(path)
    path.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(prefix='.' + path.name, dir=path.parent)
    try:
        with os.fdopen(fd, 'w') as f:
            f.write(text); f.flush(); os.fsync(f.fileno())
        os.replace(tmp, path)
        d = os.open(path.parent, os.O_DIRECTORY)
        try: os.fsync(d)
        finally: os.close(d)
    finally:
        if os.path.exists(tmp): os.unlink(tmp)


def lua(value):
    if isinstance(value, str):
        return '"' + ''.join(('\\%03d' % b) if b < 32 or b in (34, 92) else chr(b)
                             for b in value.encode('utf-8')) + '"'
    if value is True: return 'true'
    if value is False: return 'false'
    if value is None: return 'nil'
    if isinstance(value, (int, float)): return str(value)
    if isinstance(value, list): return '{' + ','.join(map(lua, value)) + '}'
    return '{' + ','.join('[' + lua(k) + ']=' + lua(v) for k, v in value.items()) + '}'


def lua_utf8(value):
    # lua() preserves byte values; decode the generated byte string once.
    return lua(value).encode('latin1').decode('utf-8')


def encode_state(state):
    return '-- ' + json.dumps(state, ensure_ascii=True) + '\nreturn ' + lua_utf8(state) + '\n'


def canonical(trigger):
    if not isinstance(trigger, str) or len(trigger) > 180:
        raise Error('Invalid key combination.')
    parts = [p.strip() for p in trigger.split('+')]
    if not parts or not parts[-1]: raise Error('Capture a key or enter a key combination.')
    mods = set()
    for p in parts[:-1]:
        p = ALIASES.get(p.upper(), p.upper())
        if p not in MODS: raise Error('Unknown modifier: ' + p)
        mods.add(p)
    key = parts[-1]
    if re.fullmatch(r'code:[0-9]+', key):
        if not 8 <= int(key[5:]) <= 767: raise Error('Invalid key code.')
    else:
        xkb = ctypes.CDLL('libxkbcommon.so.0')
        xkb.xkb_keysym_from_name.argtypes = [ctypes.c_char_p, ctypes.c_int]
        xkb.xkb_keysym_from_name.restype = ctypes.c_uint32
        sym = xkb.xkb_keysym_from_name(key.encode(), 1)
        if not sym: raise Error('Unknown XKB key: ' + key)
        buf = ctypes.create_string_buffer(128)
        xkb.xkb_keysym_get_name(sym, buf, 128)
        key = buf.value.decode()
        if len(key) == 1: key = key.upper()
    return ' + '.join([m for m in MODS if m in mods] + [key])


def key_parts(trigger):
    parts = trigger.upper().split(' + ')
    return sum(MODS.get(m, 0) for m in parts[:-1]), parts[-1]


def revision(state):
    return hashlib.sha256(json.dumps(state, sort_keys=True).encode()).hexdigest()


def apps():
    roots = [Path(os.environ.get('XDG_DATA_HOME', str(Path.home()/'.local/share')))]
    roots += [Path(p) for p in os.environ.get('XDG_DATA_DIRS', '/usr/local/share:/usr/share').split(':')]
    result, seen = [], set()
    desktop = set(os.environ.get('XDG_CURRENT_DESKTOP', 'Hyprland').split(':'))
    for root in roots:
        base = root/'applications'
        if not base.exists(): continue
        for path in sorted(base.rglob('*.desktop')):
            app_id = str(path.relative_to(base)).replace('/', '-')
            if app_id in seen: continue
            seen.add(app_id)
            cfg = configparser.ConfigParser(interpolation=None, strict=False)
            try:
                cfg.read(path, encoding='utf-8')
                d = cfg['Desktop Entry']
                if d.get('Type') != 'Application' or d.getboolean('Hidden', False) or d.getboolean('NoDisplay', False): continue
                if d.get('OnlyShowIn') and not desktop.intersection(d['OnlyShowIn'].strip(';').split(';')): continue
                if desktop.intersection(d.get('NotShowIn', '').strip(';').split(';')): continue
                if d.get('TryExec') and not shutil.which(d['TryExec']): continue
                if not d.get('Exec') and not d.getboolean('DBusActivatable', False): continue
                result.append({'id': app_id, 'name': d.get('Name', app_id), 'icon': d.get('Icon', 'application-x-executable'), 'path': str(path), 'category': d.get('Categories', '')})
            except (configparser.Error, ValueError, OSError): continue
    return sorted(result, key=lambda a: a['name'].casefold())


class Controller:
    def __init__(self, config=None):
        self.config = Path(config or os.environ.get('XDG_CONFIG_HOME', str(Path.home()/'.config')))
        self.dir = self.config/'omabinds'
        self.main = self.config/'hypr/hyprland.lua'
        self.statefile = self.dir/'state.lua'
        self.catalogfile = self.dir/'catalog.json'
        self.journal = self.dir/'transaction.json'

    @property
    def launcher(self):
        data = Path(os.environ.get('XDG_DATA_HOME', str(Path.home()/'.local/share')))
        return data/'applications/omabinds.desktop'

    @contextlib.contextmanager
    def lock(self):
        self.dir.mkdir(parents=True, exist_ok=True, mode=0o700)
        with (self.dir/'lock').open('a') as f:
            fcntl.flock(f, fcntl.LOCK_EX)
            yield

    def state(self):
        if not self.statefile.exists(): return {'version': 1, 'mappings': []}
        try: return json.loads(self.statefile.read_text().splitlines()[0][3:])
        except (ValueError, IndexError): raise Error('Corrupted state. Restore an export or the state.previous.lua copy.')

    def catalog(self):
        if not self.catalogfile.exists(): return {'bindings': [], 'warnings': []}
        return json.loads(self.catalogfile.read_text())

    def live(self):
        return json.loads(run(['hyprctl', '-j', 'binds']))

    def config_ok(self):
        raw = run(['hyprctl', 'configerrors']).strip()
        if raw and raw != 'ok': raise Error('Hyprland: ' + raw)

    def verify(self, statefile=None, main_text=None):
        text = main_text if main_text is not None else self.main.read_text()
        if statefile is None and BEGIN + 'CAPTURE' in text: statefile = self.statefile
        if statefile:
            text = '_G.omabinds_candidate = ' + lua_utf8(str(statefile)) + '\n' + text
        fd, path = tempfile.mkstemp(suffix='.lua', prefix='verify-', dir=self.dir)
        os.close(fd)
        try:
            Path(path).write_text(text)
            output = run(['Hyprland', '--verify-config', '-c', path])
            if 'config has errors' in output.lower(): raise Error(output[-4000:])
        finally: Path(path).unlink(missing_ok=True)

    def hooks(self):
        runtime = str(ROOT/'lua/runtime.lua')
        start = (BEGIN + 'CAPTURE\n' + 'omabinds_runtime = dofile(' + lua_utf8(runtime) + ')\n-- END omabinds CAPTURE\n')
        end = ('\n' + BEGIN + 'APPLY\n' + 'do local catalog = ' + lua_utf8(str(self.catalogfile)) + '; if omabinds_candidate then catalog = nil end\n' + 'omabinds_runtime.finish(omabinds_candidate or ' + lua_utf8(str(self.statefile)) + ', catalog, omabinds_candidate ~= nil) end\n-- END omabinds APPLY\n')
        return start, end

    def installed(self):
        return self.main.exists() and BEGIN + 'CAPTURE' in self.main.read_text()

    def launcher_installed(self):
        try:
            return self.launcher.is_file() and 'X-omabinds-Owned=true' in self.launcher.read_text()
        except OSError:
            return False

    def setup_status(self):
        lua = self.installed()
        launcher = self.launcher_installed()
        return {'lua': lua, 'launcher': launcher, 'ready': lua and launcher}

    def install(self):
        if self.installed():
            # configerrors can contain a historical failure from an unrelated
            # `hyprctl eval`. Validate the candidate file itself first; after
            # reload, configerrors describes this generation.
            self.verify()
            run(['hyprctl', 'reload']); self.config_ok()
            return {'message': 'Integration updated and verified.'}
        old = self.main.read_text()
        if not self.statefile.exists(): atomic(self.statefile, encode_state(self.state()))
        start, end = self.hooks()
        new = start + old + end
        self.verify(main_text=new)
        atomic(self.dir/'hyprland.before-install.lua', old)
        try:
            atomic(self.main, new)
            run(['hyprctl', 'reload']); self.config_ok()
        except Exception:
            atomic(self.main, old); run(['hyprctl', 'reload']); raise
        return {'message': 'Integration installed; no keys have been assigned.'}

    def recover(self):
        if self.journal.exists():
            previous = json.loads(self.journal.read_text())['previous']
            atomic(self.statefile, previous)
            run(['hyprctl', 'reload']); self.config_ok()
            (self.dir/'pending.lua').unlink(missing_ok=True)
            self.journal.unlink()

    def validate(self, state):
        if not isinstance(state, dict) or state.get('version') != 1 or not isinstance(state.get('mappings'), list):
            raise Error('Unsupported format; version: 1 and mappings: [] are required.')
        if len(state['mappings']) > 5000: raise Error('Maximum: 5000 keybinds.')
        ids = set()
        applications = None
        checked_commands = set()
        for m in state['mappings']:
            if not isinstance(m, dict): raise Error('Invalid keybind.')
            if not re.fullmatch(r'[a-zA-Z0-9_-]{1,64}', str(m.get('id', ''))) or m['id'] in ids: raise Error('Invalid or duplicate identifier.')
            ids.add(m['id'])
            if not isinstance(m.get('name'), str) or not 1 <= len(m['name'].strip()) <= 160: raise Error('Every keybind needs a name (maximum 160 characters).')
            if type(m.get('enabled')) is not bool: raise Error('enabled must be a boolean.')
            m['trigger'] = canonical(m.get('trigger', ''))
            a = m.get('action', {})
            if a.get('kind') == 'app':
                if applications is None: applications = {a['id']: a for a in apps()}
                if a.get('desktop') not in applications:
                    if m['enabled']: raise Error('Application not installed: ' + str(a.get('desktop')))
                    a['command'] = ''
                else: a['command'] = 'gio launch ' + shlex.quote(applications[a['desktop']]['path'])
            elif a.get('kind') == 'command':
                if not isinstance(a.get('command'), str) or not a['command'].strip() or len(a['command']) > 16384 or '\x00' in a['command']: raise Error('Empty or invalid command.')
                if a['command'] not in checked_commands:
                    run(['sh', '-n'], input=a['command']); checked_commands.add(a['command'])
            elif a.get('kind') == 'alias':
                if not isinstance(a.get('source'), str) or not isinstance(a.get('signature'), str): raise Error('Invalid alias.')
            else: raise Error('Unknown action type.')
            if not isinstance(m.get('replaces', {}), dict): raise Error('Invalid replacements.')
        return state

    def conflicts(self, state):
        conflicts, used, codes = [], {}, []
        catalog = self.catalog()['bindings']
        live = self.live()
        # Compare physical keycodes with keysyms using the active layout(s).
        overlap = KeyOverlap()
        known_handles = {(key_parts(row['trigger']), h.get('dispatcher'), h.get('arg'))
                         for row in catalog for h in row.get('runtime', [])}
        dynamic = []
        for b in live:
            if b.get('description', '').startswith('[omabinds:'): continue
            key = 'code:' + str(b['keycode']) if b.get('keycode') else b['key']
            trigger = ' + '.join([k for k, v in MODS.items() if b['modmask'] & v] + [key])
            if (key_parts(trigger), b.get('dispatcher'), b.get('arg')) not in known_handles:
                dynamic.append((b, trigger))
        for m in state['mappings']:
            if not m['enabled']: continue
            key = key_parts(m['trigger'])
            candidates = list(used.values()) if key[1].startswith('CODE:') else codes + ([used[key]] if key in used else [])
            for other in candidates:
                if overlap.same(m['trigger'], other['trigger']):
                    conflicts.append({'mapping': m['id'], 'id': other['id'], 'name': other['name'], 'trigger': other['trigger'], 'managed': True})
            used[key] = m
            if key[1].startswith('CODE:'): codes.append(m)
            for row in catalog:
                same = overlap.same(m['trigger'], row['trigger'])
                if row.get('ignoreMods'):
                    same = overlap.same(m['trigger'].split(' + ')[-1], row['trigger'].split(' + ')[-1])
                if (same or row.get('catchAll')) and m.get('replaces', {}).get(row['id']) != row['signature']:
                    conflicts.append(dict(row, mapping=m['id'], managed=False))
            # Dynamic bindings created outside the configuration must also block.
            for b, trigger in dynamic:
                if overlap.same(m['trigger'], trigger):
                    conflicts.append({'mapping': m['id'], 'id': '', 'name': b.get('description') or b.get('dispatcher'), 'trigger': trigger, 'managed': False, 'dynamic': True})
        return conflicts

    def snapshot(self):
        state = self.state()
        catalog = self.catalog()
        live = self.live()
        for row in catalog['bindings']:
            row['effective'] = any(any(h.get('dispatcher') == b.get('dispatcher') and h.get('arg') == b.get('arg') for h in row.get('runtime', [])) for b in live)
        for b in live:
            if b.get('description', '').startswith('[omabinds:'): continue
            if any(any(h.get('dispatcher') == b.get('dispatcher') and h.get('arg') == b.get('arg') for h in row.get('runtime', [])) for row in catalog['bindings']): continue
            key = 'code:' + str(b['keycode']) if b.get('keycode') else b['key']
            trigger = ' + '.join([k for k, v in MODS.items() if b['modmask'] & v] + [key])
            catalog['bindings'].append({'id':'dynamic:' + str(len(catalog['bindings'])), 'trigger':trigger, 'name':b.get('description') or b.get('dispatcher'), 'supported':False, 'effective':True, 'dynamic':True, 'submap':b.get('submap','')})
        commands = []
        try:
            for c in json.loads(run(['omarchy', 'commands', '--json']))['commands']:
                if c['group'] in ('launch', 'toggle', 'audio', 'capture') and '<' not in c.get('args', '') and not c.get('hidden') and not c.get('requires_sudo'):
                    label = ' · '.join(part.replace('-', ' ').title() for part in c['route'].split()[1:])
                    commands.append({'name': label, 'command': c['route']})
        except (Error, KeyError, ValueError): pass
        setup = self.setup_status()
        return {'state': state, 'revision': revision(state), 'catalog': catalog, 'apps': apps(), 'commands': commands,
                'installed': setup['lua'], 'setup': setup}

    def preview(self, req):
        state = self.validate(req['state'])
        if req.get('revision') != revision(self.state()): raise Error('The configuration changed. Refresh and try again.')
        overlap = KeyOverlap()
        catalog = {r['id']: r for r in self.catalog()['bindings']}
        for m in state['mappings']:
            # A changed trigger never carries consent to disable its old target.
            m['replaces'] = {key: sig for key, sig in m.get('replaces', {}).items()
                             if key in catalog and overlap.same(m['trigger'], catalog[key]['trigger'])}
        return {'conflicts': self.conflicts(state), 'state': state}

    def commit(self, req):
        if not self.installed(): raise Error('Install the integration with scripts/install.sh first.')
        preview = self.preview(req)
        if preview['conflicts']: return preview
        state = preview['state']
        fd, tmp = tempfile.mkstemp(suffix='.lua', prefix='candidate-', dir=self.dir)
        os.close(fd)
        try:
            atomic(tmp, encode_state(state))
            self.verify(Path(tmp))
            # Detect changes during validation before committing.
            if self.conflicts(state): raise Error('Bindings changed during validation. Try again.')
            old = self.statefile.read_text()
            atomic(self.dir/'state.previous.lua', old)
            atomic(self.journal, json.dumps({'previous': old}))
            procstart = Path('/proc/self/stat').read_text().rsplit(') ', 1)[1].split()[19]
            atomic(self.dir/'pending.lua', 'return ' + lua_utf8({'pid':os.getpid(), 'start':procstart, 'previous':str(self.dir/'state.previous.lua')}) + '\n')
            try:
                atomic(self.statefile, encode_state(state))
                run(['hyprctl', 'reload']); self.config_ok()
                warnings = self.catalog().get('warnings', [])
                if warnings: raise Error('\n'.join(warnings))
                effective = self.live()
                for m in state['mappings']:
                    present = any(b.get('description', '').startswith('[omabinds:' + m['id'] + '] ') for b in effective)
                    if present != m['enabled']: raise Error('Could not verify keybind: ' + m['name'])
            except Exception as exc:
                atomic(self.statefile, old)
                try:
                    run(['hyprctl', 'reload']); self.config_ok()
                    (self.dir/'pending.lua').unlink(missing_ok=True)
                    self.journal.unlink()
                except Exception as restore:
                    raise Error(f'{exc}\nRestore pending: {restore}. Run omabinds recover.')
                raise Error(str(exc) + '\nThe previous configuration has been restored.')
            (self.dir/'pending.lua').unlink(missing_ok=True)
            self.journal.unlink()
        finally: Path(tmp).unlink(missing_ok=True)
        return dict(self.snapshot(), message='Changes applied.')

    def uninstall(self):
        if not self.installed(): return {'message': 'The integration has already been removed.'}
        old = self.main.read_text()
        new = re.sub(r'-- BEGIN omabinds CAPTURE\n.*?-- END omabinds CAPTURE\n', '', old, flags=re.S)
        new = re.sub(r'\n-- BEGIN omabinds APPLY\n.*?-- END omabinds APPLY\n', '', new, flags=re.S)
        self.verify(main_text=new)
        try:
            atomic(self.main, new); run(['hyprctl', 'reload']); self.config_ok()
        except Exception:
            atomic(self.main, old); run(['hyprctl', 'reload']); raise
        return {'message': 'Integration removed; personal configuration preserved.'}


class KeyOverlap:
    """Conservative collision detector, including code:/keysym equivalents."""
    def __init__(self):
        self.cache = {}

    def symbols(self, code):
        if code in self.cache: return self.cache[code]
        x = ctypes.CDLL('libxkbcommon.so.0')
        class Names(ctypes.Structure):
            _fields_ = [(n, ctypes.c_char_p) for n in ('rules', 'model', 'layout', 'variant', 'options')]
        x.xkb_context_new.restype = ctypes.c_void_p
        x.xkb_keymap_new_from_names.argtypes = [ctypes.c_void_p, ctypes.POINTER(Names), ctypes.c_int]
        x.xkb_keymap_new_from_names.restype = ctypes.c_void_p
        x.xkb_keymap_num_layouts_for_key.argtypes = [ctypes.c_void_p, ctypes.c_uint]
        x.xkb_keymap_num_levels_for_key.argtypes = [ctypes.c_void_p, ctypes.c_uint, ctypes.c_uint]
        x.xkb_keymap_key_get_syms_by_level.argtypes = [ctypes.c_void_p, ctypes.c_uint, ctypes.c_uint, ctypes.c_uint, ctypes.POINTER(ctypes.POINTER(ctypes.c_uint))]
        x.xkb_keymap_unref.argtypes = x.xkb_context_unref.argtypes = [ctypes.c_void_p]
        settings = []
        for field in ('kb_rules', 'kb_model', 'kb_layout', 'kb_variant', 'kb_options'):
            settings.append(json.loads(run(['hyprctl', '-j', 'getoption', 'input:' + field])).get('str', '').encode() or None)
        ctx = x.xkb_context_new(0)
        km = x.xkb_keymap_new_from_names(ctx, ctypes.byref(Names(*settings)), 0)
        if not km: x.xkb_context_unref(ctx); raise Error('Could not verify the active keyboard map.')
        syms = set()
        try:
            for group in range(x.xkb_keymap_num_layouts_for_key(km, code)):
                for level in range(x.xkb_keymap_num_levels_for_key(km, code, group)):
                    ptr = ctypes.POINTER(ctypes.c_uint)()
                    count = x.xkb_keymap_key_get_syms_by_level(km, code, group, level, ctypes.byref(ptr))
                    for i in range(count):
                        buf = ctypes.create_string_buffer(128)
                        x.xkb_keysym_get_name(ptr[i], buf, 128); syms.add(buf.value.decode().upper())
        finally: x.xkb_keymap_unref(km); x.xkb_context_unref(ctx)
        self.cache[code] = syms
        return syms

    def same(self, a, b):
        am, ak = key_parts(a); bm, bk = key_parts(b)
        if am != bm: return False
        if ak == bk: return True
        if ak.startswith('CODE:') and not bk.startswith('CODE:'): return bk in self.symbols(int(ak[5:]))
        if bk.startswith('CODE:') and not ak.startswith('CODE:'): return ak in self.symbols(int(bk[5:]))
        return False


def main():
    c = Controller()
    try:
        req = json.load(sys.stdin) if len(sys.argv) == 1 else {'op': sys.argv[1]}
        op = req.get('op', 'snapshot')
        with c.lock():
            if op != 'recover': c.recover()
            if op == 'snapshot': result = c.snapshot()
            elif op == 'install': result = c.install()
            elif op == 'uninstall': result = c.uninstall()
            elif op == 'preview': result = c.preview(req)
            elif op == 'commit': result = c.commit(req)
            elif op == 'recover': c.recover(); result = {'message': 'State recovered.'}
            elif op == 'export':
                path = Path(req['path']).expanduser()
                with path.open('x') as f: json.dump(c.state(), f, indent=2, ensure_ascii=False)
                result = {'message': 'Exported to ' + str(path)}
            elif op == 'import':
                path = Path(req['path']).expanduser()
                if path.stat().st_size > 8_000_000: raise Error('File is too large.')
                result = {'imported': c.validate(json.loads(path.read_text()))}
            else: raise Error('Unknown operation.')
        print(json.dumps(dict(ok=True, **result), ensure_ascii=False))
    except Exception as exc:
        print(json.dumps({'ok': False, 'error': str(exc)}, ensure_ascii=False))
        return 1
    return 0


if __name__ == '__main__': sys.exit(main())
